defaults:
  - inference_base
  - _self_

run_name_: ucond_400M_tri
ckpt_name: proteina_v1.4_D21M_400M_tri.ckpt

self_cond: False

sampling_caflow:
  sampling_mode: sc  # "vf" for ODE sampling, "sc" for SDE sampling
  sc_scale_noise: 0.6  # noise scale, used if sampling_mode == "sc"
